# Generated by Django 3.1.3 on 2020-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(default='Eve Note'),
            preserve_default=False,
        ),
    ]
