# Generated by Django 3.1.3 on 2020-11-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ManyToManyField(to='notes.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
